# Generated by Django 5.2.17 on 2026-08-13 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial_notifications'),
        ('tasks', '0003_cascade_category_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False), ('type__in', ('TASK_DUE_SOON', 'TASK_OVERDUE'))), fields=('recipient', 'type', 'task'), name='unique_due_notification_per_task_recipient_type'),
        ),
    ]
